# Generated by Django 4.1 on 2022-11-14 20:46

from django.db import migrations, models
import django.db.models.deletion
import handler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=200)),
                ('answers', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('alt', models.TextField()),
                ('image', models.ImageField(upload_to=handler.models.directory_path)),
                ('slug', models.SlugField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.IntegerField()),
                ('recipe_name', models.CharField(default='Title', max_length=200)),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRanked',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handler.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('userId', models.CharField(max_length=100)),
                ('answers', models.JSONField()),
                ('pageId', models.CharField(max_length=100)),
                ('train_on_submission', models.BooleanField(default=False)),
                ('final_submission', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='UserRankings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=200)),
                ('movieId', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=200)),
                ('recommendation_model', models.CharField(default='NaN', max_length=200)),
                ('user_description_short', models.CharField(default='', max_length=500)),
                ('user_description_long', models.CharField(default='', max_length=1000)),
                ('recipes', models.ManyToManyField(to='handler.reciperanked')),
            ],
        ),
    ]
