# Generated by Django 4.1 on 2022-11-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=200)),
                ('answers', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=200)),
                ('recommendation_model', models.CharField(default='NaN', max_length=200)),
                ('user_description_short', models.CharField(default='', max_length=500)),
                ('user_description_long', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('userId', models.CharField(max_length=100)),
                ('answers', models.JSONField()),
                ('pageId', models.CharField(max_length=100)),
                ('train_on_submission', models.BooleanField(default=False)),
                ('final_submission', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='UserRankings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=200)),
                ('movieId', models.IntegerField()),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
