# Generated by Django 4.1 on 2022-10-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendations',
            name='user_description_long',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='recommendations',
            name='user_description_short',
            field=models.CharField(default='', max_length=500),
        ),
    ]
